// list page
export const INIT_COLLABORATORS= 'INIT_COLLABORATORS'
export const ADD_COLLABORATORS = 'ADD_COLLABORATORS'
export const SET_APPLICATION_COUNT = 'SET_APPLICATION_COUNT'
export const FETCHING_COLLABORATORS = 'FETCHING_COLLABORATORS'
export const FINISHED_FETCHING_COLLABORATORS = 'FINISHED_FETCHING_COLLABORATORS'
export const SET_NEXT_PAGING_API = 'SET_NEXT_PAGING_API'
export const DONE_LOADING_ALL_DATA = 'DONE_LOADING_ALL_DATA'

// detail page
export const SET_GOAL_APPROVAL = 'SET_GOAL_APPROVAL'
export const TO_LIST_PAGE = 'TO_LIST_PAGE'
export const INIT_TO_LIST_PAGE = 'INIT_TO_LIST_PAGE'
export const POSTING_SET_AS_TARGET = 'POSTING_SET_AS_TARGET'
export const POSTING_REMOVE_FROM_TARGET = 'POSTING_REMOVE_FROM_TARGET'
export const FINISHED_POSTING_SET_AS_TARGET = 'FINISHED_POSTING_SET_AS_TARGET'
export const FINISHED_POSTING_REMOVE_FROM_TARGET = 'FINISHED_POSTING_REMOVE_FROM_TARGET'
export const INVALID = 'INVALID'
export const INIT_DETAIL_PAGE = 'INIT_DETAIL_PAGE'
