// list page
export const INIT_GOAL_APPROVALS = 'INIT_GOAL_APPROVALS'
export const ADD_GOAL_APPROVALS = 'ADD_GOAL_APPROVALS'
export const SET_INCOMPLETE_COUNT = 'SET_INCOMPLETE'
export const FETCHING_GOAL_APPROVALS = 'FETCHING_GOAL_APPROVALS'
export const FINISHED_FETCHING_GOAL_APPROVALS = 'FINISHED_FETCHING_GOAL_APPROVALS'
export const SET_LAST_LOADED_GOAL_ID = 'SET_LAST_LOADED_GOAL_ID'
export const SET_NEXT_PAGING_API = 'SET_NEXT_PAGING_API'
export const DONE_LOADING_ALL_DATA = 'DONE_LOADING_ALL_DATA'

// detail page
export const SET_GOAL_APPROVAL = 'SET_GOAL_APPROVAL'
