// list page
export const SET_FETCH_DATA = 'SET_FETCH_DATA'
export const FETCHING_GOAL_MEMBERS = 'FETCHING_GOAL_MEMBERS'
export const FINISHED_FETCHING_GOAL_MEMBERS = 'FINISHED_FETCHING_GOAL_MEMBERS'

// detail page
export const SET_GOAL_MEMBER = 'SET_GOAL_MEMBER'
export const TO_LIST_PAGE = 'TO_LIST_PAGE'
export const INIT_TO_LIST_PAGE = 'INIT_TO_LIST_PAGE'
export const POSTING_SET_AS_TARGET = 'POSTING_SET_AS_TARGET'
export const POSTING_REMOVE_FROM_TARGET = 'POSTING_REMOVE_FROM_TARGET'
export const POSTING_WITHDRAW = 'POSTING_WITHDRAW'
export const FINISHED_POSTING_WITHDRAW = 'FINISHED_POSTING_WITHDRAW'
export const FINISHED_POSTING_SET_AS_TARGET = 'FINISHED_POSTING_SET_AS_TARGET'
export const FINISHED_POSTING_REMOVE_FROM_TARGET = 'FINISHED_POSTING_REMOVE_FROM_TARGET'
export const INVALID = 'INVALID'
export const INIT_DETAIL_PAGE = 'INIT_DETAIL_PAGE'
