export const REQUEST_SUGGEST = 'REQUEST_SUGGEST';
export const CLEAR_SUGGEST = 'CLEAR_SUGGEST';
export const SELECT_SUGGEST = 'SELECT_SUGGEST';
export const UPDATE_INPUT_DATA = 'UPDATE_INPUT_DATA';
export const SET_KEYWORD = 'SET_KEYWORD';
export const ADD_LABEL = 'ADD_LABEL';
export const DELETE_LABEL = 'DELETE_LABEL';
