// validate
export const VALID = 'VALID'
export const INVALID = 'INVALID'

// auth
export const INPUT_CODE = 'INPUT_CODE'
export const CHECKING_AUTH_CODE = 'CHECKING_AUTH_CODE'
export const FINISHED_CHECKING_AUTH_CODE = 'FINISHED_CHECKING_AUTH_CODE'
export const INIT_AUTH_CODE = 'INIT_AUTH_CODE'
export const INIT_ALL_STATUS = 'INIT_ALL_STATUS'
export const AUTH_CODE_IS_LOCKED = 'AUTH_CODE_IS_LOCKED'
export const AUTH_CODE_IS_UNLOCKED = 'AUTH_CODE_IS_UNLOCKED'
export const AUTH_CODE_IS_EXPIRED = 'AUTH_CODE_IS_EXPIRED'
export const AUTH_CODE_IS_ENABLED = 'AUTH_CODE_IS_ENABLED'
export const AUTH_CODE_IS_VALID = 'AUTH_CODE_IS_VALID'
export const AUTH_CODE_IS_INVALID = 'AUTH_CODE_IS_INVALID'
export const AUTH_TO_NEXT_PAGE = 'AUTH_TO_NEXT_PAGE'

// user_name
export const CHECKING_USER_NAME = 'CHECKING_USER_NAME'
export const FINISHED_CHECKING_USER_NAME = 'FINISHED_CHECKING_USER_NAME'
export const INIT_USER_STATUS = 'INIT_USER_STATUS'
export const USER_NETWORK_ERROR = 'USER_NETWORK_ERROR'
export const USER_TO_NEXT_PAGE = 'USER_TO_NEXT_PAGE'

// password
export const CHECKING_PASSWORD = 'CHECKING_PASSWORD'
export const FINISHED_CHECKING_PASSWORD = 'FINISHED_CHECKING_PASSWORD'
export const CAN_SUBMIT_PASSWORD = 'CAN_SUBMIT_PASSWORD'
export const CAN_NOT_SUBMIT_PASSWORD = 'CAN_NOT_SUBMIT_PASSWORD'
export const PASSWORD_NETWORK_ERROR = 'PASSWORD_NETWORK_ERROR'
export const PASSWORD_TO_NEXT_PAGE = 'PASSWORD_TO_NEXT_PAGE'

// team_name
export const CHECKING_TEAM_NAME = 'CHECKING_TEAM_NAME'
export const FINISHED_CHECKING_TEAM_NAME = 'FINISHED_CHECKING_TEAM_NAME'
export const TEAM_NAME_NETWORK_ERROR = 'TEAM_NAME_NETWORK_ERROR'
export const TEAM_TO_NEXT_PAGE = 'TEAM_TO_NEXT_PAGE'

// term
export const CHECKING_TERM = 'CHECKING_TERM'
export const FINISHED_CHECKING_TERM = 'FINISHED_CHECKING_TERM'
export const TERM_NETWORK_ERROR = 'TERM_NETWORK_ERROR'
export const CHANGE_TO_TIMEZONE_EDIT_MODE = 'CHANGE_TO_TIMEZONE_EDIT_MODE'
export const CHANGE_TO_TIMEZONE_NOT_EDIT_MODE = 'CHANGE_TO_TIMEZONE_NOT_EDIT_MODE'
export const SET_NEXT_RANGE_LIST = 'SET_NEXT_RANGE_LIST'
export const TERM_TO_NEXT_PAGE = 'TERM_TO_NEXT_PAGE'
