const gulp = require('gulp')
const browserify = require('browserify')
const babelify = require('babelify')
const source = require('vinyl-source-stream')
const duration = require('gulp-duration')
const config = require('../config.js')

gulp.task('react_setup:browserify', () => {
  return browserify({entries: [config.react_setup.src]})
    .transform(babelify, {presets: ["es2015", "react"], plugins: ["babel-plugin-transform-object-assign"]})
    .bundle()
    .pipe(source(config.react_setup.output.file_name + '.js'))
    .pipe(gulp.dest(config.dest + '/react_setup'))
    .pipe(duration('react_setup:browserify'))
})
