# Copies remaining files to places other tasks can use
module.exports = dist: files: [
  expand: true
  dot: true
  cwd: '<%= config.app %>'
  dest: '<%= config.dist %>'
  src: [
    'content/**/**.*'
    '.htaccess'
    'images/{,*/}*.webp'
    'styles/fonts/{,*/}*.*'
  ]
]

# ---
# generated by js2coffee 2.0.3
