export const VALIDATE_PAYMENT = 'VALIDATE_PAYMENT'
export const TO_NEXT_PAGE = 'TO_NEXT_PAGE'
export const INVALID = 'INVALID'
export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA'
export const DISABLE_SUBMIT = 'DISABLE_SUBMIT';
export const UPDATE_INPUT_DATA = 'UPDATE_INPUT_DATA';
export const MOVE_PAGE_BY_PAYMENT_TYPE = 'MOVE_PAGE_BY_PAYMENT_TYPE';
