export const TO_NEXT_PAGE = 'TO_NEXT_PAGE'
export const INVALID = 'INVALID'
export const FETCH_INPUT_INITIAL_DATA = 'FETCH_INPUT_INITIAL_DATA'
export const FETCH_CONFIRM_INITIAL_DATA = 'FETCH_CONFIRM_INITIAL_DATA'
export const UPDATE_INPUT_DATA = 'UPDATE_INPUT_DATA';
export const REDIRECT_TO_HOME = 'REDIRECT_TO_HOME'
