// auth
export const INPUT_CODE = 'INPUT_CODE'
export const CHECKING_AUTH_CODE = 'CHECKING_AUTH_CODE'
export const FINISHED_CHECKING_AUTH_CODE = 'FINISHED_CHECKING_AUTH_CODE'
export const INIT_AUTH_CODE = 'INIT_AUTH_CODE'
export const AUTH_CODE_IS_INVALID = 'AUTH_CODE_IS_INVALID'
export const INIT_AUTH_CODE_INVALID = 'INIT_AUTH_CODE_INVALID'
export const EMAIL_IS_LOCKED = 'EMAIL_IS_LOCKED'
export const EMAIL_IS_UNLOCKED = 'EMAIL_IS_UNLOCKED'

// password
export const INPUT_PASSWORD = 'INPUT_PASSWORD'
export const PASSWORD_IS_INVALID = 'PASSWORD_IS_INVALID'
export const CHECKING_PASSWORD = 'CHECKING_PASSWORD'

// team_name
export const INPUT_TEAM_NAME = 'INPUT_TEAM_NAME'
export const TEAM_NAME_IS_INVALID = 'TEAM_NAME_IS_INVALID'
export const CHECKING_INPUT_TEAM_NAME = 'CHECKING_INPUT_TEAM_NAME'

// term
export const SELECT_TERM = 'SELECT_TERM'
export const SELECT_START_MONTH = 'SELECT_START_MONTH'
export const SELECT_TIMEZONE = 'SELECT_TIMEZONE'
export const CHECKING_SELECTED_TERM = 'CHECKING_SELECTED_TERM'
