// auth
export const INPUT_CODE = 'INPUT_CODE'
export const CHECKING_AUTH_CODE = 'CHECKING_AUTH_CODE'
export const FINISHED_CHECKING_AUTH_CODE = 'FINISHED_CHECKING_AUTH_CODE'
export const INIT_AUTH_CODE = 'INIT_AUTH_CODE'
export const AUTH_CODE_IS_INVALID = 'AUTH_CODE_IS_INVALID'
export const INIT_AUTH_CODE_INVALID = 'INIT_AUTH_CODE_INVALID'
export const EMAIL_IS_LOCKED = 'EMAIL_IS_LOCKED'
export const EMAIL_IS_UNLOCKED = 'EMAIL_IS_UNLOCKED'

// password
export const INPUT_PASSWORD = 'INPUT_PASSWORD'
export const PASSWORD_IS_INVALID = 'PASSWORD_IS_INVALID'
export const CHECKING_PASSWORD = 'CHECKING_PASSWORD'
