export const FETCH_SETUP_STATUS = 'FETCH_SETUP_STATUS'
export const SET_VALIDATION_ERRORS = 'SET_VALIDATION_ERRORS'

// circle
export const SELECT_CIRCLE = 'SELECT_CIRCLE'
export const CREATE_CIRCLE = 'CREATE_CIRCLE'
export const FETCH_CIRCLES = 'FETCH_CIRCLES'
export const JOIN_CIRCLE = 'JOIN_CIRCLE'
export const CAN_SUBMIT_CIRCLE = 'CAN_SUBMIT_CIRCLE'
export const CAN_NOT_SUBMIT_CIRCLE = 'CAN_NOT_SUBMIT_CIRCLE'
export const CAN_JOIN_CIRCLE = 'CAN_JOIN_CIRCLE'
export const CAN_NOT_JOIN_CIRCLE = 'CAN_NOT_JOIN_CIRCLE'

// profile
export const CAN_SUBMIT_PROFILE = 'CAN_SUBMIT_PROFILE'
export const CAN_NOT_SUBMIT_PROFILE = 'CAN_NOT_SUBMIT_PROFILE'
export const ADD_PROFILE = 'ADD_PROFILE'
export const FETCH_DEFAULT_PROFILE = 'FETCH_DEFAULT_PROFILE'
export const CHANGED_TEXTAREA = 'CHANGED_TEXTAREA'

// goal
export const SELECT_PURPOSE = 'SELECT_PURPOSE'
export const SELECT_GOAL = 'SELECT_GOAL'
export const CREATE_GOAL = 'CREATE_GOAL'
export const INITIALIZE_SELECTED_GOAL = 'INITIALIZE_SELECTED_GOAL'
export const FETCHED_GOALS = 'FETCHED_GOALS'

// action
export const SELECT_ACTION_GOAL = 'SELECT_ACTION_GOAL'
export const FETCH_GOALS = 'FETCH_GOALS'
export const CAN_SUBMIT_ACTION = 'CAN_SUBMIT_ACTION'
export const CAN_NOT_SUBMIT_ACTION = 'CAN_NOT_SUBMIT_ACTION'

// post
export const CAN_SUBMIT_POST = 'CAN_SUBMIT_POST'
export const CAN_NOT_SUBMIT_POST = 'CAN_NOT_SUBMIT_POST'
export const SELECT_CIRCLE_FOR_POST = 'SELECT_CIRCLE_FOR_POST'
export const FETCH_CIRCLES_FOR_POST = 'FETCH_CIRCLES_FOR_POST'
export const FETCH_FILE_UPLOAD_ELEMENT = 'FETCH_FILE_UPLOAD_ELEMENT'
