<?php

class UserData
{
    public $name = 'User';

    public $records = [
        [
            'id'               => '1',
            'first_name'       => 'admin',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '1',
            'active_flg'       => 1,
            'admin_flg'        => 1,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'admin',
        ],
        [
            'id'               => '2',
            'first_name'       => 'a',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '2',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '3',
            'first_name'       => 'b',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '3',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '4',
            'first_name'       => 'c',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '4',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '5',
            'first_name'       => 'd',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '5',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '6',
            'first_name'       => 'e',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '6',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 2,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '7',
            'first_name'       => 'f',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '7',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 2,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '8',
            'first_name'       => 'g',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '8',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 2,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '9',
            'first_name'       => 'h',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '9',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => null,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
        [
            'id'               => '10',
            'first_name'       => 'i',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '5bdcf8151ac5a5de04462e70506c024c1371c7c417d34fde028099e0c353be08',
            'primary_email_id' => '2',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => null,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'test user',
        ],
    ];
}
