<?php

class UserData
{
    public $name = 'User';

    public $records = [
        [
            'id'               => '1',
            'first_name'       => 'admin',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '1',
            'active_flg'       => 1,
            'admin_flg'        => 1,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => '管理者テストユーザ',
        ],
        [
            'id'               => '2',
            'first_name'       => 'a',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '2',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '3',
            'first_name'       => 'b',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '3',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '4',
            'first_name'       => 'c',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '4',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '5',
            'first_name'       => 'd',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '5',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 1,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '6',
            'first_name'       => 'e',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '6',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 2,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '7',
            'first_name'       => 'f',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '7',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 2,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '8',
            'first_name'       => 'g',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '8',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => 2,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '9',
            'first_name'       => 'h',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '9',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => null,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
        [
            'id'               => '10',
            'first_name'       => 'i',
            'last_name'        => 'test',
            'gender_type'      => 1,
            'birth_day'        => '2014-05-22',
            'password'         => '85e4542a7a28cdb80d8c26d8c509d5bc9ab9139b',
            'primary_email_id' => '2',
            'active_flg'       => 1,
            'admin_flg'        => 0,
            'default_team_id'  => null,
            'timezone'         => 9,
            'language'         => 'jpn',
            'comment'          => 'テストユーザ',
        ],
    ];
}