export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA'
export const UPDATE_INPUT_DATA = 'UPDATE_INPUT_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'
export const SEARCH = 'SEARCH'
export const FETCH_MORE_GOALS = 'FETCH_MORE_GOALS'

