export const FETCH_SETUP_STATUS = 'FETCH_SETUP_STATUS'

// circle
export const SELECT_CIRCLE = 'SELECT_CIRCLE'
export const CREATE_CIRCLE = 'CREATE_CIRCLE'
export const FETCH_CIRCLES = 'FETCH_CIRCLES'
export const JOIN_CIRCLE = 'JOIN_CIRCLE'

// profile
export const CAN_SUBMIT_PROFILE = 'CAN_SUBMIT_PROFILE'
export const CAN_NOT_SUBMIT_PROFILE = 'CAN_NOT_SUBMIT_PROFILE'
export const ADD_PROFILE = 'ADD_PROFILE'

// goal
export const SELECT_PURPOSE = 'SELECT_PURPOSE'
export const SELECT_GOAL = 'SELECT_GOAL'
export const CREATE_GOAL = 'CREATE_GOAL'
