export const FETCH_INITIAL_DATA = 'FETCH_INITIAL_DATA'
export const UPDATE_INPUT_DATA = 'UPDATE_INPUT_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'
export const UPDATE_KEYWORD = 'UPDATE_KEYWORD'
export const SEARCH = 'SEARCH'
export const FETCH_MORE_RESULTS = 'FETCH_MORE_RESULTS'
export const LOADING = 'LOADING'
export const LOADING_MORE = 'LOADING_MORE'

